# Generated by Django 5.0.14 on 2025-07-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('Matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Civilite', models.CharField(max_length=10)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('NoAffiliationCNSS', models.CharField(blank=True, max_length=50, null=True)),
                ('DateEntree', models.DateField(blank=True, null=True)),
                ('SituationEffectifLibelle', models.CharField(blank=True, max_length=100, null=True)),
                ('AffectationCode', models.CharField(blank=True, max_length=100, null=True)),
                ('AffectationLibelle', models.CharField(blank=True, max_length=200, null=True)),
                ('ArborescenceAffectation', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Agent',
                'managed': False,
            },
        ),
    ]
