# Generated by Django 5.0.14 on 2025-09-05 11:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vivier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCommission', models.CharField(help_text='Format: 001/2025', max_length=9, unique=True, verbose_name='Num Commission')),
                ('DateCreation', models.DateField(default=django.utils.timezone.now)),
                ('FonctionCible', models.CharField(max_length=120)),
                ('DirectionReseau', models.CharField(max_length=120)),
                ('Valide', models.BooleanField(default=False)),
                ('DateValidation', models.DateField(blank=True, null=True)),
                ('Observation', models.TextField(blank=True)),
                ('PieceJointe', models.FileField(blank=True, null=True, upload_to='vivier/')),
            ],
            options={
                'db_table': 'Vivier',
                'ordering': ('-DateCreation', '-NumCommission'),
                'indexes': [models.Index(fields=['Valide'], name='Vivier_Valide_096f75_idx'), models.Index(fields=['DateCreation'], name='Vivier_DateCre_7b5fa8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricule', models.CharField(max_length=10)),
                ('Trajectoire', models.BooleanField(blank=True, null=True)),
                ('Sanction', models.CharField(blank=True, max_length=120)),
                ('PI_n_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PI_n_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PI_n_3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('AvisCommission', models.CharField(blank=True, max_length=120)),
                ('Decision', models.CharField(blank=True, max_length=120)),
                ('Note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('MotifDecision', models.TextField(blank=True)),
                ('Caractere', models.CharField(blank=True, max_length=120)),
                ('vivier', models.ForeignKey(db_column='NumeroCommission', on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='vivier.vivier', to_field='NumCommission', verbose_name='Numero Commission')),
            ],
            options={
                'db_table': 'Commission',
                'ordering': ('vivier', 'Matricule'),
                'indexes': [models.Index(fields=['Matricule'], name='Commission_Matricu_3857a4_idx'), models.Index(fields=['vivier'], name='Commission_NumeroC_287336_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.UniqueConstraint(fields=('vivier', 'Matricule'), name='uq_commission_vivier_matricule'),
        ),
    ]
