# Generated by Django 5.0.14 on 2025-09-06 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vivier',
            options={'managed': True},
        ),
        migrations.RemoveConstraint(
            model_name='commission',
            name='uq_commission_vivier_matricule',
        ),
        migrations.RemoveIndex(
            model_name='commission',
            name='Commission_Matricu_3857a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='commission',
            name='Commission_NumeroC_287336_idx',
        ),
        migrations.RemoveIndex(
            model_name='vivier',
            name='Vivier_Valide_096f75_idx',
        ),
        migrations.RemoveIndex(
            model_name='vivier',
            name='Vivier_DateCre_7b5fa8_idx',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='vivier',
        ),
        migrations.RemoveField(
            model_name='vivier',
            name='PieceJointe',
        ),
        migrations.AddField(
            model_name='vivier',
            name='PJ_data',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
        migrations.AddField(
            model_name='vivier',
            name='PJ_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vivier',
            name='PJ_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vivier',
            name='PJ_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='AvisCommission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='Caractere',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='Decision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='Matricule',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commission',
            name='MotifDecision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='Sanction',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='Trajectoire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vivier',
            name='DateCreation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vivier',
            name='DirectionReseau',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vivier',
            name='Observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='Vivier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vivier.vivier'),
        ),
    ]
