# Generated by Django 5.0.14 on 2025-09-14 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivier', '0002_alter_commission_options_alter_vivier_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VivierPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vivier/pj/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=150)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vivier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='vivier.vivier')),
            ],
        ),
    ]
