# Generated by Django 5.0.14 on 2025-09-14 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivier', '0003_vivierpiece'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('taille', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.BinaryField(blank=True, max_length='max', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vivier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='vivier.vivier')),
            ],
            options={
                'db_table': 'PieceJointe',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='VivierPiece',
        ),
    ]
