# Generated by Django 5.0.14 on 2025-08-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('NumeroAffectation', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('DateAffectation', models.DateField()),
                ('DateLettreAffectation', models.DateField(blank=True, null=True)),
                ('Matricule', models.CharField(max_length=50)),
                ('CodeFonctionAncien', models.CharField(blank=True, max_length=50, null=True)),
                ('LibelleFonctionAncien', models.CharField(blank=True, max_length=150, null=True)),
                ('DateFonctionAncien', models.DateField(blank=True, null=True)),
                ('CodeEntiteAncien', models.CharField(blank=True, max_length=10, null=True)),
                ('LibelleEntiteAncien', models.CharField(blank=True, max_length=100, null=True)),
                ('DateAffectationAncien', models.DateField(blank=True, null=True)),
                ('CodeFonctionNouveau', models.CharField(blank=True, max_length=50, null=True)),
                ('LibelleFonctionNouveau', models.CharField(blank=True, max_length=150, null=True)),
                ('DateFonctionNouveau', models.DateField(blank=True, null=True)),
                ('CodeEntiteNouveau', models.CharField(blank=True, max_length=10, null=True)),
                ('LibelleEntiteNouveau', models.CharField(blank=True, max_length=100, null=True)),
                ('DateAffectationNouveau', models.DateField(blank=True, null=True)),
                ('ChangementAffectation', models.BooleanField(default=False)),
                ('ChangementFonction', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Affectation',
                'ordering': ['-CreatedAt'],
            },
        ),
    ]
