# Generated by Django 5.0.14 on 2025-08-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affectation',
            old_name='DateAffectation',
            new_name='DateMobilite',
        ),
        migrations.RemoveField(
            model_name='affectation',
            name='DateAffectationNouveau',
        ),
        migrations.RemoveField(
            model_name='affectation',
            name='DateFonctionNouveau',
        ),
    ]
