# Generated by Django 5.0.14 on 2025-09-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0002_rename_dateaffectation_affectation_datemobilite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectation',
            options={'managed': False, 'ordering': ['-DateLettreAffectation', '-NumeroAffectation']},
        ),
    ]
