# Generated by Django 5.0.14 on 2025-07-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('AffectationCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('AffectationLibelle', models.CharField(max_length=100)),
                ('ArborescenceAffectation', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Entite',
                'managed': False,
            },
        ),
    ]
