# Generated by Django 5.0.14 on 2025-07-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=100)),
                ('intitule_complet', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Fonction',
                'managed': False,
            },
        ),
    ]
